# GET http://localhost:8080/user
curl http://localhost:8080/user -u 'customer1:customer1'

# {
#     "id": "90e00b3f-b409-4bac-8b3a-246686b3c69e",
#     "username": "customer1",
#     "name": "Customer One",
#     "projects":
#     [
#         {
#             "id": "3380a9af-3f91-4ebf-810b-0239bb1e5bde",
#             "title": "The grand project",
#             "description": "The project is to construct a patio in the\nbackyard, and a fire place.\n",
#             "expectedHours": 55,
#             "biddingEndTime": "2022-12-19T10:32:58.335399Z",
#             "bids":
#             [
#                 {
#                     "id": "6daecff5-7309-4482-9e2c-e808c3304f41",
#                     "amount": 0,
#                     "project": "3380a9af-3f91-4ebf-810b-0239bb1e5bde"
#                 }
#             ]
#         }
#     ],
#     "type": "customer"
# }
#"{{$localDatetime rfc1123|iso8601 [integer y|M|w|d|h|m|s|ms]}}"'
###

curl http://localhost:8080/projects \
-u 'customer1:customer1' \
-H 'Content-Type: application/json; charset=utf-8' \
--data-binary @- << EOF
{
   "title": "The grand project",
   "description": "The project is to construct a patio in the\nbackyard, and a fire place.\n",
   "expectedHours": 55,
   "biddingEndTime": "{{$datetime iso8601 10d}}"
}
EOF

###

POST http://localhost:8080/projects
Authorization: Basic customer1:customer1
Content-Type: application/json; charset=utf-8

{
   "title": "The grand project",
   "description": "The project is to construct a patio in the\nbackyard, and a fire place.\n",
   "expectedHours": 55,
   "biddingEndTime": "{{$datetime iso8601 10 s}}"
}


###

GET http://localhost:8080/user
Authorization: Basic tradie1:tradie1

# {
#   "id": "242f12cf-2300-4879-863a-a115f62b413c",
#   "username": "tradie1",
#   "name": "Tradie One",
#   "trade": "carpenter",
#   "experience": 4,
#   "activeBids": [
#     {
#       "id": "0d8d1281-b319-4ae1-bc7f-2a9bce0eea34",
#       "amount": 100,
#       "project": {
#         "id": "3380a9af-3f91-4ebf-810b-0239bb1e5bde",
#         "title": "The grand project",
#         "description": "The project is to construct a patio in the\nbackyard, and a fire place.\n",
#         "expectedHours": 55,
#         "biddingEndTime": "2022-12-19T10:32:58.335399Z",
#         "bids": [
#           "0d8d1281-b319-4ae1-bc7f-2a9bce0eea34",
#           {
#             "id": "6daecff5-7309-4482-9e2c-e808c3304f41",
#             "amount": 0,
#             "project": "3380a9af-3f91-4ebf-810b-0239bb1e5bde"
#           }
#         ]
#       }
#     },
#     "6daecff5-7309-4482-9e2c-e808c3304f41"
#   ],
#   "type": "tradie"
# }

###

POST http://localhost:8080/bids
Authorization: Basic tradie1:tradie1
Content-Type: application/json; charset=utf-8

{
    "projectId": "3380a9af-3f91-4ebf-810b-0239bb1e5bde",
    "amount": 100
}

###

GET http://localhost:8080/bids
Authorization: Basic tradie1:tradie1
